sonar.projectKey=nawrees_Patch_space
sonar.organization=nawrees

sonar.sources=backend/src,backend/tests,frontend/src,database/scripts
sonar.exclusions=**/node_modules/**,frontend/dist/**,frontend/.angular/**
sonar.sourceEncoding=UTF-8
